name: 'Terraform'

on:
  push:
    branches:
      - infra
  pull_request:
    branches:
      - infra

jobs:
  terraform:
    name: 'Terraform'
    environment: 
      name: aws
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.12.0

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          TF_LOG: DEBUG  # Habilita la salida detallada de Terraform
        run: |
          cd $GITHUB_WORKSPACE
          terraform plan
        continue-on-error: true  # Continúa la ejecución incluso si hay errores
      
      - name: Display Terraform Errors
        if: ${{ failure() }}
        run: |
          echo "Errores durante la ejecución de Terraform:"
          cat $GITHUB_WORKSPACE/terraform.log
      

    #   - name: Terraform Plan
    #     env:
    #       AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #       AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #       TF_LOG: DEBUG  # Habilita la salida detallada de Terraform
    #     run: terraform plan

    #   - name: Terraform Apply
    #     env:
    #       AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #       AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #       TF_LOG: DEBUG  # Habilita la salida detallada de Terraform
    #     run: terraform apply -auto-approve
